In [39]:
import tensorflow as tf
import numpy as np

In [40]:
a=tf.Variable(0,name='counter')
print(a)
print(a.name)


<tf.Variable 'counter_7:0' shape=() dtype=int32_ref>
counter_7:0


In [41]:
b=tf.constant(1)
print(b)

Tensor("Const_4:0", shape=(), dtype=int32)


In [42]:
d=tf.Variable(np.ones(shape=(2,3)),dtype=tf.float32,name='weights')
e=tf.constant('Hello, TensorFlow!')


In [43]:
c=a+b

In [44]:
init=tf.initialize_all_variables()
global_init=tf.global_variables_initializer()
saver=tf.train.Saver()#会话之前定义
with tf.Session() as sess:
    sess.run(global_init)
    sess.run(init)
    print(sess.run(a))#1+0=1
    print(sess.run(d))

0
[[1. 1. 1.]
 [1. 1. 1.]]


In [46]:
#定义图
#placeholder作为图的输入,op中，op运算的类型有：1、可以输入的placeholder类型  2、定义的参数类型variable和constant
x1 = tf.placeholder(tf.int16)
x2 = tf.placeholder(tf.int16)

#定义了图op
add = tf.add(x1, x2)
mul = tf.multiply(x1, x2)

#运行图
with tf.Session() as sess:
    # Run every operation with variable input
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={x1: 2, x2: 3}))
    print('加法结果:{}'.format( sess.run(add, feed_dict={x1: 2, x2: 3}) ))


Multiplication with variables: 6
加法结果:5


In [59]:
#常量图
matrix1 = tf.constant([[3., 3.]])#默认ditype=32
matrix2 = tf.constant(np.array([[2],[2]],dtype=np.float32))   #tf的是tf.float32,np的是np.float32

#op
product = tf.matmul(matrix1, matrix2)#二维矩阵乘法，横乘以竖
with tf.Session() as sess:#这里constant不用初始化，变量variable才要
    result = sess.run(product)
    print(sess.run(matrix2))
    print(result)





[[2.]
 [2.]]
[[12.]]
